import {
  imgurClientID,
  imgurClientSecret,
  // imgurAccessToken,
  imgurAlbumID,
  imgurAuthorizationCode,
  imgurRefreshToken,
  spoonacularAPIKey,
  googleAPIKey,
} from "../config/config.js";

export class AppStateManager {
  constructor() {
    // Credentials
    this.imgurClientID = imgurClientID;
    this.imgurClientSecret = imgurClientSecret;
    // this.imgurAccessToken = imgurAccessToken;
    this.imgurAlbumID = imgurAlbumID;
    this.imgurAuthorizationCode = imgurAuthorizationCode;
    this.imgurRefreshToken = imgurRefreshToken;
    this.googleAPIKey = googleAPIKey;
    this.spoonacularAPIKey = spoonacularAPIKey;

    // state
    this.imgurAccessToken = null;
    this.favoriteArray = [];
    this.restrictionsString = "";
    this.intolerancesString = "";
    this.chunkedRecipeArray = [];
    this.chunkedRecipeArrayIndex = 0;
    this.favoriteYPosition = null;
    this.rect = {};

    // array of top 1000 common ingredients
    const ingredients = [
      "apple",
      "banana",
      "orange",
      "lemon",
      "lime",
      "garlic",
      "onion",
      "tomato",
      "potato",
      "carrot",
      "broccoli",
      "cauliflower",
      "bell pepper",
      "spinach",
      "kale",
      "lettuce",
      "cucumber",
      "zucchini",
      "eggplant",
      "avocado",
      "mushrooms",
      "celery",
      "corn",
      "peas",
      "green beans",
      "asparagus",
      "sweet potato",
      "radish",
      "beets",
      "butternut squash",
      "pumpkin",
      "ginger",
      "parsley",
      "cilantro",
      "basil",
      "oregano",
      "thyme",
      "rosemary",
      "dill",
      "mint",
      "chives",
      "scallions",
      "leeks",
      "chili peppers",
      "jalapeno",
      "serrano peppers",
      "habanero",
      "cayenne pepper",
      "paprika",
      "cumin",
      "coriander",
      "turmeric",
      "curry powder",
      "cinnamon",
      "nutmeg",
      "cloves",
      "cardamom",
      "bay leaves",
      "black pepper",
      "white pepper",
      "red pepper flakes",
      "salt",
      "sugar",
      "honey",
      "maple syrup",
      "agave syrup",
      "vinegar (white, balsamic, red wine)",
      "olive oil",
      "coconut oil",
      "vegetable oil",
      "butter",
      "margarine",
      "cream",
      "milk",
      "yogurt",
      "sour cream",
      "mayonnaise",
      "ketchup",
      "mustard",
      "barbecue sauce",
      "soy sauce",
      "fish sauce",
      "hot sauce",
      "worcestershire sauce",
      "tahini",
      "peanut butter",
      "almond butter",
      "jam",
      "jelly",
      "marmalade",
      "bread",
      "flour",
      "whole wheat flour",
      "cornmeal",
      "baking powder",
      "baking soda",
      "yeast",
      "cornstarch",
      "oats",
      "quinoa",
      "rice (white, brown)",
      "pasta",
      "couscous",
      "bulgur",
      "farro",
      "barley",
      "lentils",
      "chickpeas",
      "black beans",
      "kidney beans",
      "pinto beans",
      "cannellini beans",
      "lima beans",
      "split peas",
      "tofu",
      "tempeh",
      "seitan",
      "chicken breast",
      "chicken thigh",
      "chicken wings",
      "chicken drumsticks",
      "whole chicken",
      "turkey",
      "ground turkey",
      "ground beef",
      "steak",
      "ribeye",
      "filet mignon",
      "sirloin",
      "pork chops",
      "bacon",
      "ham",
      "sausage",
      "ground pork",
      "lamb",
      "lamb chops",
      "ground lamb",
      "salmon",
      "tuna",
      "cod",
      "haddock",
      "shrimp",
      "scallops",
      "crab",
      "lobster",
      "clams",
      "mussels",
      "oysters",
      "eggs",
      "cheese (cheddar, mozzarella, parmesan, etc.)",
      "ricotta",
      "cottage cheese",
      "feta",
      "blue cheese",
      "goat cheese",
      "brie",
      "gouda",
      "swiss cheese",
      "cream cheese",
      "sour cream",
      "parmesan",
      "mozzarella",
      "heavy cream",
      "half-and-half",
      "milk (whole, 2%, skim, almond, soy, oat)",
      "egg whites",
      "egg yolks",
      "pancetta",
      "prosciutto",
      "salami",
      "pepperoni",
      "capicola",
      "shrimp",
      "crabmeat",
      "scallops",
      "lobster",
      "mussels",
      "clams",
      "sardines",
      "anchovies",
      "tuna (canned)",
      "mackerel",
      "squid",
      "octopus",
      "bacon bits",
      "dried fruit (raisins, cranberries, apricots)",
      "almonds",
      "cashews",
      "pecans",
      "walnuts",
      "pistachios",
      "sunflower seeds",
      "pumpkin seeds",
      "chia seeds",
      "flaxseeds",
      "sesame seeds",
      "poppy seeds",
      "hemp seeds",
      "granola",
      "breakfast cereal",
      "grits",
      "polenta",
      "crackers",
      "tortillas",
      "naan",
      "pita bread",
      "bagels",
      "english muffins",
      "croissants",
      "pretzels",
      "baguette",
      "buns",
      "wraps",
      "pizza dough",
      "pie crust",
      "phyllo dough",
      "puff pastry",
      "shortbread",
      "biscuits",
      "muffins",
      "scones",
      "doughnuts",
      "pancakes",
      "waffles",
      "french toast",
      "crepes",
      "brown sugar",
      "powdered sugar",
      "vanilla extract",
      "almond extract",
      "cocoa powder",
      "chocolate chips",
      "dark chocolate",
      "white chocolate",
      "milk chocolate",
      "caramel",
      "marshmallows",
      "gelatin",
      "pudding mix",
      "jello mix",
      "whipped cream",
      "frosting",
      "ice cream",
      "sorbet",
      "gelato",
      "custard",
      "macaroni",
      "ravioli",
      "tortellini",
      "fettuccine",
      "spaghetti",
      "penne",
      "rigatoni",
      "lasagna noodles",
      "ramen",
      "udon",
      "soba",
      "rice noodles",
      "egg noodles",
      "potato chips",
      "tortilla chips",
      "popcorn",
      "crackers",
      "pretzels",
      "cornbread",
      "breadsticks",
      "canned tomatoes",
      "tomato paste",
      "tomato sauce",
      "marinara sauce",
      "alfredo sauce",
      "soy sauce",
      "tamari",
      "fish sauce",
      "hoisin sauce",
      "oyster sauce",
      "teriyaki sauce",
      "chili sauce",
      "sriracha",
      "ketchup",
      "mustard",
      "mayonnaise",
      "hot sauce",
      "bbq sauce",
      "honey mustard",
      "relish",
      "salsa",
      "guacamole",
      "hummus",
      "pesto",
      "tapenade",
      "capers",
      "olives (black, green)",
      "pickles",
      "jalapeños",
      "sauerkraut",
      "kimchi",
      "canned beans",
      "canned corn",
      "canned peas",
      "canned tuna",
      "canned salmon",
      "canned chicken",
      "canned clams",
      "canned shrimp",
      "canned mushrooms",
      "artichoke hearts",
      "water chestnuts",
      "bamboo shoots",
      "canned pineapple",
      "coconut milk",
      "coconut cream",
      "curry paste",
      "red curry paste",
      "green curry paste",
      "yellow curry paste",
      "coconut flakes",
      "shredded coconut",
      "chocolate syrup",
      "maple syrup",
      "agave nectar",
      "molasses",
      "corn syrup",
      "granola bars",
      "protein bars",
      "trail mix",
      "dried apricots",
      "dried cranberries",
      "dried mango",
      "dried pineapple",
      "freeze-dried fruit",
      "instant potatoes",
      "couscous",
      "polenta",
      "quinoa",
      "barley",
      "rice (basmati, jasmine)",
      "wild rice",
      "risotto",
      "cornmeal",
      "tapioca",
      "arborio rice",
      "gnocchi",
      "lentils",
      "split peas",
      "mung beans",
      "black-eyed peas",
      "edamame",
      "cannellini beans",
      "navy beans",
      "adzuki beans",
      "pinto beans",
      "kidney beans",
      "white beans",
      "black beans",
      "soybeans",
      "chickpeas",
      "fava beans",
      "butter beans",
      "tempeh",
      "seitan",
      "tofu",
      "paneer",
      "parmesan",
      "mozzarella",
      "cheddar",
      "swiss cheese",
      "brie",
      "gouda",
      "blue cheese",
      "cream cheese",
      "feta cheese",
      "goat cheese",
      "provolone",
      "ricotta",
      "cottage cheese",
      "mascarpone",
      "sour cream",
      "heavy cream",
      "whipping cream",
      "half-and-half",
      "evaporated milk",
      "condensed milk",
      "buttermilk",
      "almond milk",
      "soy milk",
      "oat milk",
      "coconut milk",
      "rice milk",
      "peanut butter",
      "almond butter",
      "cashew butter",
      "tahini",
      "hazelnuts",
      "macadamia nuts",
      "pecans",
      "pine nuts",
      "pistachios",
      "walnuts",
      "sunflower seeds",
      "pumpkin seeds",
      "flaxseeds",
      "chia seeds",
      "sesame seeds",
      "poppy seeds",
      "hemp seeds",
      "basil pesto",
      "tapenade",
      "olive tapenade",
      "sun-dried tomatoes",
      "artichoke hearts",
      "avocados",
      "bananas",
      "blueberries",
      "blackberries",
      "strawberries",
      "raspberries",
      "cherries",
      "mango",
      "pineapple",
      "papaya",
      "kiwi",
      "pomegranate",
      "figs",
      "dates",
      "coconut",
      "melons",
      "cantaloupe",
      "honeydew",
      "watermelon",
      "grapefruit",
      "grapes",
      "lemons",
      "limes",
      "oranges",
      "clementines",
      "mandarins",
      "tangerines",
      "peaches",
      "nectarines",
      "plums",
      "apricots",
      "persimmons",
      "starfruit",
      "passionfruit",
      "guava",
      "dragon fruit",
      "jackfruit",
      "lychee",
      "durian",
      "rhubarb",
      "plantains",
      "soursop",
      "breadfruit",
      "rose apple",
      "sapote",
      "mangosteen",
      "turmeric",
      "mace",
      "mustard seeds",
      "fenugreek",
      "saffron",
      "garam masala",
      "herbes de provence",
      "za'atar",
      "baharat",
      "ras el hanout",
      "dukkah",
      "chili powder",
      "curry powder",
    ];

    // binding class methods
    this.setState = this.setState.bind(this);
    this.getState = this.getState.bind(this);
  }

  setState(key, value) {
    if (this.hasOwnProperty(key)) {
      this[key] = value;
    } else {
      console.warn(`State key "${key}" does not exist`);
    }
  }

  getState(key) {
    return this[key];
  }
}
