name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace placeholders in main.js
        env:
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
          IMGUR_CLIENT_SECRET: ${{ secrets.IMGUR_CLIENT_SECRET }}
          IMGUR_ALBUM_ID: ${{ secrets.IMGUR_ALBUM_ID }}
          IMGUR_AUTHORIZATION_CODE: ${{ secrets.IMGUR_AUTHORIZATION_CODE }}
          IMGUR_REFRESH_TOKEN: ${{ secrets.IMGUR_REFRESH_TOKEN }}
          SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          sed -i "s|__IMGUR_CLIENT_ID__|$IMGUR_CLIENT_ID|" ./src/main.js
          sed -i "s|__IMGUR_CLIENT_SECRET__|$IMGUR_CLIENT_SECRET|" ./src/main.js
          sed -i "s|__IMGUR_ALBUM_ID__|$IMGUR_ALBUM_ID|" ./src/main.js
          sed -i "s|__IMGUR_AUTHORIZATION_CODE__|$IMGUR_AUTHORIZATION_CODE|" ./src/main.js
          sed -i "s|__IMGUR_REFRESH_TOKEN__|$IMGUR_REFRESH_TOKEN|" ./src/main.js
          sed -i "s|__SPOONACULAR_API_KEY__|$SPOONACULAR_API_KEY|" ./src/main.js
          sed -i "s|__GOOGLE_API_KEY__|$GOOGLE_API_KEY|" ./src/main.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
