# Simple workflow for deploying static content to Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace placeholders in main.js
        shell: bash
        run: |
          sed -i "s|__IMGUR_CLIENT_ID__|${{ secrets.IMGUR_CLIENT_ID }}|g" ./src/main.js
          sed -i "s|__IMGUR_CLIENT_SECRET__|${{ secrets.IMGUR_CLIENT_SECRET }}|g" ./src/main.js
          sed -i "s|__IMGUR_ALBUM_ID__|${{ secrets.IMGUR_ALBUM_ID }}|g" ./src/main.js
          sed -i "s|__IMGUR_AUTHORIZATION_CODE__|${{ secrets.IMGUR_AUTHORIZATION_CODE }}|g" ./src/main.js
          sed -i "s|__IMGUR_REFRESH_TOKEN__|${{ secrets.IMGUR_REFRESH_TOKEN }}|g" ./src/main.js
          sed -i "s|__SPOONACULAR_API_KEY__|${{ secrets.SPOONACULAR_API_KEY }}|g" ./src/main.js
          sed -i "s|__GOOGLE_API_KEY__|${{ secrets.GOOGLE_API_KEY }}|g" ./src/main.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
