name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        env:
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
          IMGUR_CLIENT_SECRET: ${{ secrets.IMGUR_CLIENT_SECRET }}
          IMGUR_ALBUM_ID: ${{ secrets.IMGUR_ALBUM_ID }}
          IMGUR_AUTHORIZATION_CODE: ${{ secrets.IMGUR_AUTHORIZATION_CODE }}
          IMGUR_REFRESH_TOKEN: ${{ secrets.IMGUR_REFRESH_TOKEN }}
          SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          echo "Building project"
          # You can use the environment variables in your script here
          npm run build
          npm run deploy
