name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
      IMGUR_CLIENT_SECRET: ${{ secrets.IMGUR_CLIENT_SECRET }}
      IMGUR_ALBUM_ID: ${{ secrets.IMGUR_ALBUM_ID }}
      IMGUR_AUTHORIZATION_CODE: ${{ secrets.IMGUR_AUTHORIZATION_CODE }}
      IMGUR_REFRESH_TOKEN: ${{ secrets.IMGUR_REFRESH_TOKEN }}
      SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace placeholders in main.js
        shell: bash
        run: |
          sed -i "s|__IMGUR_CLIENT_ID__|${IMGUR_CLIENT_ID}|g" ./src/main.js
          sed -i "s|__IMGUR_CLIENT_SECRET__|${IMGUR_CLIENT_SECRET}|g" ./src/main.js
          sed -i "s|__IMGUR_ALBUM_ID__|${IMGUR_ALBUM_ID}|g" ./src/main.js
          sed -i "s|__IMGUR_AUTHORIZATION_CODE__|${IMGUR_AUTHORIZATION_CODE}|g" ./src/main.js
          sed -i "s|__IMGUR_REFRESH_TOKEN__|${IMGUR_REFRESH_TOKEN}|g" ./src/main.js
          sed -i "s|__SPOONACULAR_API_KEY__|${SPOONACULAR_API_KEY}|g" ./src/main.js
          sed -i "s|__GOOGLE_API_KEY__|${GOOGLE_API_KEY}|g" ./src/main.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
